import Head from 'next/head'
import Newsletter from "@/components/common/Newsletter";
import Header from "@/components/company/Header";
import Footer from "@/components/Footer/Footer";
import Navigation from "@/components/Navigation/Navigation";
import Body from "./about/Body";
import MobileNavigatin from '@/components/Navigation/MobileNavigation';

export default function About() {
    return (
        <>
            <Head>
                <title>About Company</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MobileNavigatin />
            <Navigation />
            {/* <Header
                title="Who we are "
                description="A team of Creative Minds designing the best Digital Growth Solutions 
                Provider for the World.
                "
            /> */}
            <Body />
            <Newsletter />
            <Footer />
        </>
    )
};
