import Newsletter from '@/components/common/Newsletter'
import Header from '@/components/company/Header'
import Footer from '@/components/Footer/Footer'
import MobileNavigatin from '@/components/Navigation/MobileNavigation'
import Navigation from '@/components/Navigation/Navigation'
import Head from 'next/head'
import Body from './contact/Body'

export default function Contact() {
    return (
        <>
            <Head>
                <title>Contact Us</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MobileNavigatin />
            <Navigation />
            {/* <Header
                title="Contact Us"
            /> */}
            <Body />
            <Footer />
        </>
    )
};
