import Head from 'next/head'
import Newsletter from "@/components/common/Newsletter";
import Footer from "@/components/Footer/Footer";
import Navigation from "@/components/Navigation/Navigation";
import Body from "./customPlan/Body";
import MobileNavigatin from '@/components/Navigation/MobileNavigation';


export default function CustomPlan() {
    return (
        <>
            <Head>
                <title>Custom Plan</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MobileNavigatin />
            <Navigation />
            <Body />
            {/* <Newsletter /> */}
            <Footer />
        </>
    )
};
