import Footer from "@/components/Footer/Footer";
import MobileNavigatin from "@/components/Navigation/MobileNavigation";
import Navigation from "@/components/Navigation/Navigation";
import Header from "./Giveaway/Header";
import Head from 'next/head'
import Inside from "./Giveaway/Inside";
import TakeParticipation from "./Giveaway/TakeParticipation";
import EnquiryForm from "./Giveaway/EnquiryForm";

export default function Giveaway() {
    return (
        <>
            <Head>
                <title>Giveaway</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MobileNavigatin />
            <Navigation />
            <Header />
            <Inside />
            <TakeParticipation />
            <EnquiryForm />
            <Footer />

        </>
    )
};
