import Faq from '@/components/common/Faq'
import Newsletter from '@/components/common/Newsletter'
import Footer from '@/components/Footer/Footer'
import MobileNavigatin from '@/components/Navigation/MobileNavigation'
import Navigation from '@/components/Navigation/Navigation'
import Head from 'next/head'
import Header from "@/components/company/Header";
import Categories from './Home/Categories'

export default function Industries() {
  return (
    <>
      <Head>
        <title>Digitally Grow Fast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MobileNavigatin />
      <Navigation />
      <Header
        title="Industries"
      />
      <Categories />
      <Faq />
      {/* <Newsletter /> */}
      <Footer />
    </>
  )
}
