import Head from 'next/head'
import MobileNavigatin from "@/components/Navigation/MobileNavigation";
import Navigation from "@/components/Navigation/Navigation";
import Plan from '@/components/common/Plan'
import Newsletter from "@/components/common/Newsletter";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/company/Header";


export default function PlanContent() {
    return (
        <>
            <Head>
                <title>Plan | DGF</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MobileNavigatin />
            <Navigation />
            {/* <Header
                title="Our Plans"
            /> */}
            <Plan />
            <Newsletter />
            <Footer />
        </>
    )
};
