import Head from 'next/head'
import Newsletter from "@/components/common/Newsletter";
import Footer from "@/components/Footer/Footer";
import MobileNavigatin from "@/components/Navigation/MobileNavigation";
import Navigation from "@/components/Navigation/Navigation";
import Header from "@/components/company/Header";
import PrivacyPolicyContent from './company/PrivacyPolicyContent';

export default function PrivacyPolicy() {
    return (
        <>
            <Head>
                <title>Privacy Policy</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MobileNavigatin />
            <Navigation />
            <Header
                title="Privacy Policy"
            />
            <PrivacyPolicyContent />
            <Newsletter />
            <Footer />
        </>
    )
};
