
import Footer from "@/components/Footer/Footer";
import MobileNavigatin from "@/components/Navigation/MobileNavigation";
import Navigation from "@/components/Navigation/Navigation";
import Body from "./growth-plan/Body";
import Head from 'next/head'

export default function OnlineGrowthPlan() {
    return (
        <>
            <Head>
                <title>Online Growth Plan</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MobileNavigatin />
            <Navigation />
            <Body />
            <Footer />
        </>
    )
};
